name: fcore build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Test Lib
        run: cargo test --lib

  build-node:
    needs: [tests]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build Node
        run: |
          cross build --release \
            --bin node \
            --target ${{ matrix.target }} \
            --features xray,wireguard,amnezia-wg

      - name: Verify binary
        run: |
          file target/${{ matrix.target }}/release/node
          ldd target/${{ matrix.target }}/release/node || true

  build-api:
    needs: [tests]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2
        with:
          key: api

      - name: Install cross
        run: cargo install cross

      - name: Build API
        run: |
          cross build --release \
             --bin api \
             --no-default-features \
             --target x86_64-unknown-linux-musl

      - name: Verify binary
        run: |
          file target/x86_64-unknown-linux-musl/release/api
          ldd target/x86_64-unknown-linux-musl/release/api || true

  build-auth:
    needs: [tests]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2
        with:
          key: auth

      - name: Install cross
        run: cargo install cross

      - name: Build Auth
        run: |
          cross build --release \
            --bin auth \
            --no-default-features \
            --target x86_64-unknown-linux-musl

      - name: Verify binary
        run: |
          file target/x86_64-unknown-linux-musl/release/auth
          ldd target/x86_64-unknown-linux-musl/release/auth || true
